# Generated by Django 3.1 on 2020-08-23 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1000, null=True)),
            ],
            options={
                'db_table': 'ARTIST',
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=2000, null=True)),
                ('is_custom', models.BooleanField(null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('is_use', models.BooleanField()),
                ('ARTIST', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.artist')),
            ],
            options={
                'db_table': 'ARTWORK',
            },
        ),
        migrations.CreateModel(
            name='ArtworkColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('info', models.CharField(max_length=1000, null=True)),
            ],
            options={
                'db_table': 'ARTWORK_COLOR',
            },
        ),
        migrations.CreateModel(
            name='ArtworkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'ARTWORK_TYPE',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('is_use', models.BooleanField()),
            ],
            options={
                'db_table': 'DEVICE',
            },
        ),
        migrations.CreateModel(
            name='DeviceBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'DEVICE_BRAND',
            },
        ),
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'FEATURED',
            },
        ),
        migrations.CreateModel(
            name='DeviceColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('DEVICE', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.device')),
            ],
            options={
                'db_table': 'DEVICE_COLOR',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='DEVICE_BRAND',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.devicebrand'),
        ),
        migrations.AddField(
            model_name='device',
            name='DEVICE_COLOR',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.devicecolor'),
        ),
        migrations.CreateModel(
            name='ArtworkReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('comment', models.TextField(max_length=1000, null=True)),
                ('rate', models.PositiveSmallIntegerField(null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('is_use', models.BooleanField()),
                ('ARTWORK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.artwork')),
                ('USER', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
            ],
            options={
                'db_table': 'ARTWORK_REVIEW',
            },
        ),
        migrations.CreateModel(
            name='ArtworkPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('ARTWORK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.artwork')),
                ('DEVICE', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.device')),
            ],
            options={
                'db_table': 'ARTWORK_PRICE',
            },
        ),
        migrations.CreateModel(
            name='ArtworkImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url_1', models.URLField(max_length=2500, null=True)),
                ('image_url_2', models.URLField(max_length=2500, null=True)),
                ('image_url_3', models.URLField(max_length=2500, null=True)),
                ('image_url_4', models.URLField(max_length=2500, null=True)),
                ('image_url_5', models.URLField(max_length=2500, null=True)),
                ('image_url_6', models.URLField(max_length=2500, null=True)),
                ('ARTWORK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.artwork')),
            ],
            options={
                'db_table': 'ARTWORK_IMAGE',
            },
        ),
        migrations.CreateModel(
            name='ArtworkColorDeivce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ARTWORK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.artwork')),
                ('ARTWORK_COLOR', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.artworkcolor')),
                ('DEVICE', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.device')),
            ],
            options={
                'db_table': 'ARTWORK_COLOR_DEVICE',
            },
        ),
        migrations.AddField(
            model_name='artwork',
            name='ARTWORK_COLOR',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.artworkcolor'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='ARTWORK_TYPE',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.artworktype'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='DEVICE',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.device'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='FEATURED',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.featured'),
        ),
    ]
