# Generated by Django 3.1 on 2020-08-26 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0002_auto_20200826_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='FEATURED',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.featured'),
        ),
    ]
