# Generated by Django 3.1 on 2020-08-26 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0003_device_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='DEVICE',
        ),
        migrations.AddField(
            model_name='artwork',
            name='DEVICE_MODEL',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.devicemodel'),
        ),
    ]
