# Generated by Django 3.1 on 2020-08-26 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200826_2338'),
        ('user', '0001_initial'),
        ('artwork', '0004_auto_20200826_2254'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artwork',
            new_name='Phonecase',
        ),
        migrations.RenameModel(
            old_name='ArtworkColor',
            new_name='PhonecaseColor',
        ),
        migrations.RenameModel(
            old_name='ArtworkColorDeivce',
            new_name='PhonecaseColorDeivce',
        ),
        migrations.RenameModel(
            old_name='ArtworkImage',
            new_name='PhonecaseImage',
        ),
        migrations.RenameModel(
            old_name='ArtworkPrice',
            new_name='PhonecasePrice',
        ),
        migrations.RenameModel(
            old_name='ArtworkReview',
            new_name='PhonecaseReview',
        ),
        migrations.RenameModel(
            old_name='ArtworkType',
            new_name='PhonecaseType',
        ),
        migrations.RenameField(
            model_name='phonecase',
            old_name='ARTWORK_COLOR',
            new_name='PHONECASE_COLOR',
        ),
        migrations.RenameField(
            model_name='phonecase',
            old_name='ARTWORK_TYPE',
            new_name='PHONECASE_TYPE',
        ),
        migrations.RenameField(
            model_name='phonecasecolordeivce',
            old_name='ARTWORK',
            new_name='PHONECASE',
        ),
        migrations.RenameField(
            model_name='phonecasecolordeivce',
            old_name='ARTWORK_COLOR',
            new_name='PHONECASE_COLOR',
        ),
        migrations.RenameField(
            model_name='phonecaseimage',
            old_name='ARTWORK',
            new_name='PHONECASE',
        ),
        migrations.RenameField(
            model_name='phonecaseprice',
            old_name='ARTWORK',
            new_name='PHONCASE',
        ),
        migrations.RenameField(
            model_name='phonecasereview',
            old_name='ARTWORK',
            new_name='PHONECASE',
        ),
        migrations.AlterModelTable(
            name='phonecase',
            table='PHONECASE',
        ),
        migrations.AlterModelTable(
            name='phonecasecolor',
            table='PHONECASE_COLOR',
        ),
        migrations.AlterModelTable(
            name='phonecasecolordeivce',
            table='PHONECASE_COLOR_DEVICE',
        ),
        migrations.AlterModelTable(
            name='phonecaseimage',
            table='PHONECASE_IMAGE',
        ),
        migrations.AlterModelTable(
            name='phonecaseprice',
            table='PHONECASE_PRICE',
        ),
        migrations.AlterModelTable(
            name='phonecasereview',
            table='PHONECASE_REVIEW',
        ),
        migrations.AlterModelTable(
            name='phonecasetype',
            table='PHONECASE_TYPE',
        ),
    ]
