# Generated by Django 3.1 on 2020-08-26 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0005_auto_20200826_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonecaseprice',
            old_name='PHONCASE',
            new_name='PHONECASE',
        ),
    ]
