# Generated by Django 3.1 on 2020-08-26 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0006_auto_20200826_2340'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artist',
            new_name='Artwork',
        ),
        migrations.RenameField(
            model_name='phonecase',
            old_name='ARTIST',
            new_name='ARTWORK',
        ),
        migrations.AlterModelTable(
            name='artwork',
            table='ARTWORK',
        ),
    ]
