# Generated by Django 3.1 on 2020-08-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kakao_token', models.CharField(max_length=200, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=300)),
                ('mobile_number', models.CharField(max_length=11)),
                ('first_name', models.CharField(max_length=15, null=True)),
                ('last_name', models.CharField(max_length=15, null=True)),
                ('introduction', models.CharField(max_length=1000, null=True)),
                ('website_url', models.URLField(max_length=2500, null=True)),
                ('location', models.CharField(max_length=500, null=True)),
                ('twitter', models.CharField(max_length=100, null=True)),
                ('profile_image_url', models.URLField(max_length=2500, null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('is_use', models.BooleanField()),
            ],
            options={
                'db_table': 'USER',
            },
        ),
    ]
