# Generated by Django 3.0.7 on 2020-09-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='create_datetime',
        ),
        migrations.AddField(
            model_name='user',
            name='regist_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
