# Generated by Django 3.1 on 2020-08-23 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('artwork', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_custom', models.BooleanField(null=True)),
                ('custom_info', models.TextField(max_length=2000, null=True)),
                ('quantity', models.SmallIntegerField()),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('is_use', models.BooleanField()),
                ('ARTWORK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.artwork')),
                ('ARTWORK_PRICE', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.artworkprice')),
                ('USER', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
            ],
            options={
                'db_table': 'CART',
            },
        ),
        migrations.CreateModel(
            name='CheckoutStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'CHECKOUT_STATUS',
            },
        ),
        migrations.CreateModel(
            name='Orderer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('zipcode', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('USER', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
            ],
            options={
                'db_table': 'ORDERER',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100)),
                ('delivery_price', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('sub_total_price', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('is_use', models.BooleanField()),
                ('ORDERER', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.orderer')),
                ('USER', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
            ],
            options={
                'db_table': 'ORDER',
            },
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_info', models.TextField(max_length=3000, null=True)),
                ('quantity', models.SmallIntegerField()),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('is_use', models.BooleanField()),
                ('CART', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.cart')),
                ('CHECKOUT_STATUS', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.checkoutstatus')),
                ('ORDER', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order')),
                ('USER', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
            ],
            options={
                'db_table': 'CHECKOUT',
            },
        ),
    ]
