# Generated by Django 3.1 on 2020-08-26 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='ARTWORK',
            new_name='PHONECASE',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='ARTWORK_PRICE',
            new_name='PHONECASE_PRICE',
        ),
    ]
